<a href="https://colab.research.google.com/github/SarveshMD/colab-notebooks/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.11.0+cpu


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
scalar = torch.tensor(7)
print(scalar.shape)
print(scalar.ndim)

torch.Size([])
0


In [ ]:
vector = torch.tensor([1,2,3])
print(vector.shape)
print(vector.ndim)

torch.Size([3])
1


In [ ]:
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.shape)
print(matrix.ndim)

torch.Size([3, 3])
2


In [ ]:
tensor = torch.tensor([
    [[1,2],[2,3]],
    [[1,0],[0,1]],
    [[0,0],[0,0]],
    [[-1,0],[0,-1]]
])
print(tensor.shape)
print(tensor.ndim)

torch.Size([4, 2, 2])
3


In [ ]:
rand_matrix = torch.rand((3,4))
print(rand_matrix)

tensor([[0.6476, 0.4464, 0.0391, 0.9550],
        [0.4328, 0.5873, 0.9235, 0.9040],
        [0.1869, 0.2626, 0.6204, 0.7139]])


In [ ]:
rand_tensor = torch.rand((2,3,3))
print(rand_tensor)
print(rand_tensor.ndim)

tensor([[[0.0160, 0.2837, 0.6023],
         [0.5740, 0.1973, 0.6438],
         [0.4043, 0.3228, 0.0115]],

        [[0.9448, 0.2881, 0.2323],
         [0.1249, 0.0766, 0.3249],
         [0.3426, 0.5671, 0.5580]]])
3


In [ ]:
zeros = torch.zeros((2,2,2))
ones = torch.ones((2,2,2))
zeros, ones

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 tensor([[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]))

In [ ]:
range_tensor = torch.arange(0,3*3*3).reshape((3,3,3))
range_tensor

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [ ]:
zeros_like_range = torch.zeros_like(range)
zeros_like_range

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [ ]:
float_32_tensor = torch.tensor([1,0], dtype=torch.float32)
float_32_tensor.dtype

torch.float32

In [ ]:
float_64_tensor = float_32_tensor.to(torch.float64)
float_64_tensor.dtype

torch.float64

In [ ]:
float_32_tensor + float_64_tensor

tensor([2., 0.], dtype=torch.float64)

In [ ]:
float_32_tensor.device

device(type='cpu')

In [ ]:
M1 = torch.tensor([[1,2],[3,4]])
M2 = torch.tensor([[4,3],[7,9]])

2


In [ ]:
def run():
  matrix_mux = 0
  res = torch.zeros((M1.shape[0], M2.shape[1]))
  for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
      res[i][j] = torch.dot(M1[i], M2[:, j])
%timeit run()

71.3 µs ± 12.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit torch.matmul(M1, M2)

2.91 µs ± 566 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit M1@M2

3.14 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Sum, Mean, Max, Min

In [58]:
x = torch.arange(0, 99)

In [6]:
x.max(), torch.max(x)

(tensor(98), tensor(98))

In [7]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [8]:
x.argmax(), torch.argmax(x)

(tensor(98), tensor(98))

In [14]:
x.to(torch.float32).mean()

tensor(49.)

## Reshape, Stack, Squeeze, Permute

In [20]:
x.reshape(9,11), x.reshape(11,9)

(tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
         [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
         [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
         [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
         [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
         [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]]),
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
         [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23, 24, 25, 26],
         [27, 28, 29, 30, 31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49, 50, 51, 52, 53],
         [54, 55, 56, 57, 58, 59, 60, 61, 62],
         [63, 64, 65, 66, 67, 68, 69, 70, 71],
         [72, 73, 74, 75, 76, 77, 78, 79, 80],
         [81, 82, 83, 84, 85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94, 95,

In [63]:
x = x.view(1,1,1,99)
x

tensor([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
           17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
           34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
           51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
           68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
           85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]]]])

In [53]:
y = torch.stack((x, x), dim=2)

In [64]:
x.shape, torch.squeeze(x).shape

(torch.Size([1, 1, 1, 99]), torch.Size([99]))

In [66]:
x = x.squeeze()
x.shape

torch.Size([99])

In [75]:
x.unsqueeze(dim=0)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [77]:
y = torch.arange(100).reshape(10,10)

In [81]:
y

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [84]:
y.permute(1,0)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
        [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
        [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
        [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
        [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
        [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
        [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])