<a href="https://colab.research.google.com/github/SarveshMD/colab-notebooks/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.11.0+cpu


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
scalar = torch.tensor(7)
print(scalar.shape)
print(scalar.ndim)

torch.Size([])
0


In [5]:
vector = torch.tensor([1,2,3])
print(vector.shape)
print(vector.ndim)

torch.Size([3])
1


In [6]:
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.shape)
print(matrix.ndim)

torch.Size([3, 3])
2


In [7]:
tensor = torch.tensor([
    [[1,2],[2,3]],
    [[1,0],[0,1]],
    [[0,0],[0,0]],
    [[-1,0],[0,-1]]
])
print(tensor.shape)
print(tensor.ndim)

torch.Size([4, 2, 2])
3


In [8]:
rand_matrix = torch.rand((3,4))
print(rand_matrix)

tensor([[0.6476, 0.4464, 0.0391, 0.9550],
        [0.4328, 0.5873, 0.9235, 0.9040],
        [0.1869, 0.2626, 0.6204, 0.7139]])


In [9]:
rand_tensor = torch.rand((2,3,3))
print(rand_tensor)
print(rand_tensor.ndim)

tensor([[[0.0160, 0.2837, 0.6023],
         [0.5740, 0.1973, 0.6438],
         [0.4043, 0.3228, 0.0115]],

        [[0.9448, 0.2881, 0.2323],
         [0.1249, 0.0766, 0.3249],
         [0.3426, 0.5671, 0.5580]]])
3


In [10]:
zeros = torch.zeros((2,2,2))
ones = torch.ones((2,2,2))
zeros, ones

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 tensor([[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]))

In [45]:
range_tensor = torch.arange(0,3*3*3).reshape((3,3,3))
range_tensor

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [18]:
zeros_like_range = torch.zeros_like(range)
zeros_like_range

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [34]:
float_32_tensor = torch.tensor([1,0], dtype=torch.float32)
float_32_tensor.dtype

torch.float32

In [35]:
float_64_tensor = float_32_tensor.to(torch.float64)
float_64_tensor.dtype

torch.float64

In [36]:
float_32_tensor + float_64_tensor

tensor([2., 0.], dtype=torch.float64)

In [37]:
float_32_tensor.device

device(type='cpu')

In [44]:
M1 = torch.tensor([[1,2],[3,4]])
M2 = torch.tensor([[4,3],[7,9]])

2


In [72]:
def run():
  matrix_mux = 0
  res = torch.zeros((M1.shape[0], M2.shape[1]))
  for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
      res[i][j] = torch.dot(M1[i], M2[:, j])
%timeit run()

71.3 µs ± 12.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [70]:
%timeit torch.matmul(M1, M2)

2.91 µs ± 566 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [69]:
%timeit M1@M2

3.14 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
